import type { editor } from "monaco-editor";

/** Catppuccin Mocha theme for Monaco editor */
export const CATPPUCCIN_MOCHA_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6c7086", fontStyle: "italic" },
    { token: "keyword", foreground: "cba6f7" },
    { token: "keyword.control", foreground: "cba6f7" },
    { token: "storage", foreground: "cba6f7" },
    { token: "string", foreground: "a6e3a1" },
    { token: "string.escape", foreground: "f2cdcd" },
    { token: "number", foreground: "fab387" },
    { token: "constant", foreground: "fab387" },
    { token: "type", foreground: "f9e2af" },
    { token: "type.identifier", foreground: "f9e2af" },
    { token: "class", foreground: "f9e2af" },
    { token: "function", foreground: "89b4fa" },
    { token: "variable", foreground: "cdd6f4" },
    { token: "variable.predefined", foreground: "f38ba8" },
    { token: "operator", foreground: "89dceb" },
    { token: "delimiter", foreground: "9399b2" },
    { token: "tag", foreground: "cba6f7" },
    { token: "attribute.name", foreground: "f9e2af" },
    { token: "attribute.value", foreground: "a6e3a1" },
    { token: "regexp", foreground: "f5c2e7" },
    { token: "annotation", foreground: "fab387" },
    { token: "meta", foreground: "f5c2e7" },
  ],
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "editor.lineHighlightBackground": "#313244",
    "editor.selectionBackground": "#45475a",
    "editor.selectionHighlightBackground": "#45475a80",
    "editor.inactiveSelectionBackground": "#45475a60",
    "editorCursor.foreground": "#f5e0dc",
    "editorLineNumber.foreground": "#6c7086",
    "editorLineNumber.activeForeground": "#cba6f7",
    "editorIndentGuide.background": "#31324480",
    "editorIndentGuide.activeBackground": "#45475a",
    "editorWhitespace.foreground": "#31324480",
    "editorWidget.background": "#181825",
    "editorWidget.border": "#313244",
    "editorSuggestWidget.background": "#181825",
    "editorSuggestWidget.border": "#313244",
    "editorSuggestWidget.selectedBackground": "#313244",
    "editorSuggestWidget.highlightForeground": "#cba6f7",
    "editorHoverWidget.background": "#181825",
    "editorHoverWidget.border": "#313244",
    "editor.findMatchBackground": "#f9e2af40",
    "editor.findMatchHighlightBackground": "#f9e2af20",
    "editorBracketMatch.background": "#45475a",
    "editorBracketMatch.border": "#cba6f7",
    "editorOverviewRuler.border": "#181825",
    "scrollbar.shadow": "#11111b",
    "scrollbarSlider.background": "#45475a60",
    "scrollbarSlider.hoverBackground": "#45475a80",
    "scrollbarSlider.activeBackground": "#45475aaa",
    "minimap.background": "#181825",
  },
};
